# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
    default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - smartcontractkit/chainlink-brownie-contracts@0.4.2

# path remapping to support imports from GitHub/NPM
compiler:
    solc:
        # version: 0.8.10
        remappings:
            - "@oz=OpenZeppelin/openzeppelin-contracts@4.5.0/contracts/"
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.2/contracts/"

reports:
    exclude_contracts:
        - SafeERC20
        - IERC20
        - ReentrancyGuard
        - Address
